name: imc_flutter
description: 'A new Flutter project. Created by Slidy'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_icons: ^1.1.0
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.5+1
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7+3

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/man_unselected.png
    - assets/images/man_selected.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
